/* generated configuration header file - do not edit */
#ifndef SF_AUDIO_PLAYBACK_HW_DAC_CFG_H_
#define SF_AUDIO_PLAYBACK_HW_DAC_CFG_H_
#define SF_AUDIO_PLAYBACK_HW_DAC_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define SF_AUDIO_PLAYBACK_HW_DAC_CFG_DMAC_SUPPORT_ENABLE (0)
#endif /* SF_AUDIO_PLAYBACK_HW_DAC_CFG_H_ */
