/* generated configuration header file - do not edit */
#ifndef SF_AUDIO_PLAYBACK_CFG_H_
#define SF_AUDIO_PLAYBACK_CFG_H_
#define SF_AUDIO_PLAYBACK_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define SF_AUDIO_PLAYBACK_CFG_BUFFER_SIZE_BYTES (512U)
#define SF_AUDIO_PLAYBACK_CFG_MAX_STREAMS (1U)
#endif /* SF_AUDIO_PLAYBACK_CFG_H_ */
