/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.0                                                   */
/*  Date (dd.mm.yyyy): 18. 3.2016   Time (hh:mm): 16:48                        */
/*******************************************************************************/


#ifndef _GX_STUDIO_PROJECT_SPECIFICATIONS_H_
#define _GX_STUDIO_PROJECT_SPECIFICATIONS_H_

#include "gx_api.h"


/* Define widget ids                                                           */



/* Declare properties structures for each utilized widget type                 */

typedef struct GX_STUDIO_WIDGET_STRUCT
{
   CHAR *widget_name;
   UINT  widget_type;
   UINT  widget_id;
   #if defined(GX_WIDGET_USER_DATA)
   INT   user_data;
   #endif
   ULONG style;
   ULONG status;
   ULONG control_block_size;
   GX_RESOURCE_ID normal_fill_color_id;
   GX_RESOURCE_ID selected_fill_color_id;
   UINT (*create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   void (*draw_function) (GX_WIDGET *);
   UINT (*event_function) (GX_WIDGET *, GX_EVENT *);
   GX_RECTANGLE size;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *next_widget;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *child_widget;
   GX_WIDGET *control_block;
   GX_CONST void *properties;
} GX_STUDIO_WIDGET;

typedef struct
{
    GX_RESOURCE_ID normal_pixelmap_id;
    GX_RESOURCE_ID selected_pixelmap_id;
} GX_ICON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
} GX_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID wallpaper_id;
} GX_WINDOW_PROPERTIES;


/* Declare top-level control blocks                                            */

typedef struct W_MAIN_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_ICON w_main_ico_logo;
    GX_PROGRESS_BAR w_main_bar_temp;
    GX_PROGRESS_BAR w_main_bar_buttons;
    GX_PROMPT w_main_label_1;
    GX_PROMPT w_main_label_2;
    GX_PROMPT w_main_label_3;
    GX_PROMPT w_main_label_4;
} W_MAIN_CONTROL_BLOCK;


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern W_MAIN_CONTROL_BLOCK w_main;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT w_main_event(GX_WINDOW *widget, GX_EVENT *event_ptr);

/* Declare the GX_STUDIO_DISPLAY_INFO structure                                */


typedef struct GX_STUDIO_DISPLAY_INFO_STRUCT 
{
    GX_CONST CHAR *name;
    GX_CONST CHAR *canvas_name;    GX_CONST GX_THEME **theme_table;
    GX_CONST GX_CHAR ***language_table;
    INT      language_table_size;
    INT      string_table_size;
    GX_VALUE x_resolution;
    GX_VALUE y_resolution;
    GX_DISPLAY *display;
    GX_CANVAS  *canvas;
    GX_WINDOW_ROOT *root_window;
    GX_COLOR   *canvas_memory;
    ULONG      canvas_memory_size;
} GX_STUDIO_DISPLAY_INFO;


/* Declare Studio-generated functions for creating top-level widgets           */

GX_WIDGET *gx_studio_widget_create(GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), USHORT language, USHORT theme, GX_WINDOW_ROOT **return_root);

#endif                                       /* sentry                         */
