################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../synergy/ssp/src/framework/sf_el_ux/usb_irq_veneer.c \
../synergy/ssp/src/framework/sf_el_ux/usbfs_irq_veneer.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_empty_interrupt.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_notready_interrupt.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_read.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_ready_interrupt.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_current_endpoint_change.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_data_buffersize.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_destroy.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_nak_set.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_reset.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_stall.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_status.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifo_port_change.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifo_read.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifoc_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifod_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_frame_number_get.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_function.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_initialize.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_initialize_complete.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_interrupt_handler.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_clear.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_read.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_set.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_transfer_callback.c \
../synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_transfer_request.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_bemp.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_brdy.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_nrdy.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_sign.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_schedule.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynchronous_endpoint_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynchronous_endpoint_destroy.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_empty_interrupt.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_notready_interrupt.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_read.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_ready_interrupt.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_bulk_endpoint_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_bulk_int_td_add.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_control_endpoint_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_control_td_add.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_controller_disable.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_current_endpoint_change.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_data_buffer_size.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_ed_obtain.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_ed_td_clean.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_endpoint_nak_set.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_endpoint_reset.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_entry.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifo_port_change.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifo_read.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifoc_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifod_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_frame_number_get.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_frame_number_set.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_initialize.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_interrupt_endpoint_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_interrupt_handler.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_iso_queue_process.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_iso_schedule.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_isochronous_endpoint_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_isochronous_td_obtain.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_least_traffic_list_get.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_endpoint_destroy.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_schedule.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_tree_create.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_disable.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_enable.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_reset.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_resume.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_status_get.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_suspend.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_down_port.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_on_port.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_root_hubs.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_clear.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_read.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_set.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_write.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_regular_td_obtain.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_bulk_transfer.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_control_transfer.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_interupt_transfer.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_isochronous_transfer.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_transfer.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_td_add.c \
../synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_transfer_abort.c 

OBJS += \
./synergy/ssp/src/framework/sf_el_ux/usb_irq_veneer.o \
./synergy/ssp/src/framework/sf_el_ux/usbfs_irq_veneer.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_empty_interrupt.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_notready_interrupt.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_read.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_ready_interrupt.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_current_endpoint_change.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_data_buffersize.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_destroy.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_nak_set.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_reset.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_stall.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_status.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifo_port_change.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifo_read.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifoc_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifod_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_frame_number_get.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_function.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_initialize.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_initialize_complete.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_interrupt_handler.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_clear.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_read.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_set.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_transfer_callback.o \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_transfer_request.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_bemp.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_brdy.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_nrdy.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_sign.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_schedule.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynchronous_endpoint_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynchronous_endpoint_destroy.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_empty_interrupt.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_notready_interrupt.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_read.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_ready_interrupt.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_bulk_endpoint_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_bulk_int_td_add.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_control_endpoint_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_control_td_add.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_controller_disable.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_current_endpoint_change.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_data_buffer_size.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_ed_obtain.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_ed_td_clean.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_endpoint_nak_set.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_endpoint_reset.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_entry.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifo_port_change.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifo_read.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifoc_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifod_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_frame_number_get.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_frame_number_set.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_initialize.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_interrupt_endpoint_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_interrupt_handler.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_iso_queue_process.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_iso_schedule.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_isochronous_endpoint_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_isochronous_td_obtain.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_least_traffic_list_get.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_endpoint_destroy.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_schedule.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_tree_create.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_disable.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_enable.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_reset.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_resume.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_status_get.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_suspend.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_down_port.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_on_port.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_root_hubs.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_clear.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_read.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_set.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_write.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_regular_td_obtain.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_bulk_transfer.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_control_transfer.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_interupt_transfer.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_isochronous_transfer.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_transfer.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_td_add.o \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_transfer_abort.o 

C_DEPS += \
./synergy/ssp/src/framework/sf_el_ux/usb_irq_veneer.d \
./synergy/ssp/src/framework/sf_el_ux/usbfs_irq_veneer.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_empty_interrupt.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_notready_interrupt.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_read.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_ready_interrupt.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_buffer_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_current_endpoint_change.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_data_buffersize.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_destroy.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_nak_set.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_reset.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_stall.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_endpoint_status.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifo_port_change.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifo_read.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifoc_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_fifod_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_frame_number_get.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_function.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_initialize.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_initialize_complete.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_interrupt_handler.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_clear.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_read.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_set.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_register_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_transfer_callback.d \
./synergy/ssp/src/framework/sf_el_ux/ux_dcd_synergy_transfer_request.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_bemp.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_brdy.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_nrdy.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_queue_process_sign.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynch_schedule.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynchronous_endpoint_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_asynchronous_endpoint_destroy.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_empty_interrupt.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_notready_interrupt.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_read.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_ready_interrupt.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_buffer_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_bulk_endpoint_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_bulk_int_td_add.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_control_endpoint_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_control_td_add.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_controller_disable.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_current_endpoint_change.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_data_buffer_size.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_ed_obtain.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_ed_td_clean.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_endpoint_nak_set.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_endpoint_reset.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_entry.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifo_port_change.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifo_read.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifoc_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_fifod_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_frame_number_get.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_frame_number_set.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_initialize.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_interrupt_endpoint_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_interrupt_handler.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_iso_queue_process.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_iso_schedule.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_isochronous_endpoint_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_isochronous_td_obtain.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_least_traffic_list_get.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_endpoint_destroy.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_schedule.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_periodic_tree_create.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_disable.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_enable.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_reset.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_resume.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_status_get.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_port_suspend.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_down_port.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_on_port.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_power_root_hubs.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_clear.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_read.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_set.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_register_write.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_regular_td_obtain.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_bulk_transfer.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_control_transfer.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_interupt_transfer.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_isochronous_transfer.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_request_transfer.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_td_add.d \
./synergy/ssp/src/framework/sf_el_ux/ux_hcd_synergy_transfer_abort.d 


# Each subdirectory must supply rules for building sources it contributes
synergy/ssp/src/framework/sf_el_ux/%.o: ../synergy/ssp/src/framework/sf_el_ux/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	C:\Renesas\e2_studio\eclipse\../Utilities/isdebuild arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal  -g3 -D_RENESAS_SYNERGY_ -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy_cfg\ssp_cfg\bsp" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy_cfg\ssp_cfg\driver" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\bsp" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\bsp\cmsis\Include" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\driver\api" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\driver\instances" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\src" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\src\synergy_gen" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy_cfg\ssp_cfg\framework" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\framework\api" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\framework\instances" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy_cfg\ssp_cfg\framework\el" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\inc\framework\el" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\src\framework\el\tx" -I"C:\Users\Kirti\e2_studio\workspace\SPIFrame\synergy\ssp\src\framework\el\ux" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" -x c "$<"
	@echo 'Finished building: $<'
	@echo ' '


